apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcamp-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: healthcamp
  template:
    metadata:
      labels:
        app: healthcamp
    spec:
      containers:
        - name: healthcamp
          image: dineshkuru/healthcamp-demo:latest
          env:
            - name: MONGODB_USERNAME
              valueFrom: 
                secretKeyRef:
                  name: mongo-creds
                  key: username
            - name: MONGODB_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: mongo-creds
                  key: password
            - name: MONGODB
              value: "mongo-service.default"